"""empty message

Revision ID: 1ea07dc58e7e
Revises: 441e17ea0df5
Create Date: 2019-03-11 20:55:21.166215

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '1ea07dc58e7e'
down_revision = '441e17ea0df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False))
    op.add_column('user', sa.Column('password', sqlalchemy_utils.types.password.PasswordType(max_length=1137), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
